version: '3.9'
services:

  api:
   image: ${DOCKER_REGISTRY-}avanpost-api
   build:
      context: ../
      dockerfile: API/AvanPost.API/Dockerfile
   volumes:
      - ./Images:/Images
   ports:
     - '8000:80'
        

networks:
  avanpost:
    driver: bridge
  
